buildscript {
    ext {
        buildToolsVersion = "36.0.0"      // updated
        minSdkVersion = 24
        compileSdkVersion = 36            // updated
        targetSdkVersion = 36             // updated
        ndkVersion = "27.1.12297006"     // updated
        kotlinVersion = "2.1.20"         // updated
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.3.1")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
